sudo: false

before_install:
  - pip install --upgrade pip
  - pip --version

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: pip install codecov tox-travis
script: tox
after_success:
  - codecov
