language: python
sudo: false
matrix:
  include:
  - python: 3.6
    env: NOX_SESSION=lint
  - python: 3.6
    env: NOX_SESSION=docs
  - python: 3.6
    env: NOX_SESSION=cover
  - python: 2.7
    env: NOX_SESSION="unit_tests(python='python2.7')"
  - python: 3.4
    env: NOX_SESSION="unit_tests(python='python3.4')"
  - python: 3.5
    env: NOX_SESSION="unit_tests(python='python3.5')"
  # Disabled until gRPC supports PyPy.
  # - python: pypy
  #   env: NOX_SESSION=unit_tests(python='pypy')
cache:
  directories:
  - ${HOME}/.cache
install:
- pip install --upgrade nox-automation
script: nox -s $NOX_SESSION
after_success:
- test $NOX_SESSION = "cover" && codecov
